USE BDVENTASWEB
GO

CREATE PROCEDURE USP_LISTAR_CLIENTES
AS
	SELECT C.cli_cod, C.cli_nom FROM Clientes C
GO

EXECUTE USP_LISTAR_CLIENTES
GO

CREATE PROC USP_LISTAR_ARTICULOS
@ART_NOM VARCHAR(20)='%'
AS
SELECT A.art_cod, art_nom, 
              A.art_pre, A.art_stk
FROM Articulos A
	WHERE A.art_nom LIKE @ART_NOM+'%'
GO

-- EXECUTE USP_LISTAR_ARTICULOS 'M'
-- GO

CREATE PROC USP_GRABAR_VENTA_CAB_WEB
@CLI_COD CHAR(5),@VTA_TOTAL DECIMAL(10,2)
AS
	-- DECLARANDO VARIABLE PARA EL NUEVO NUMERO DE VENTA
	DECLARE @NUMERO INT 
	-- RECUPERANDO EL MAXIMO NUMERO DE VENTA
	SELECT @NUMERO=MAX(VTA_NUM)+1 FROM Venta_cab
	-------- CALCULAR EL IGV ----------------------------------
	DECLARE @IGV DECIMAL(8,2)=0
	SELECT @IGV = (@VTA_TOTAL/1.18)*0.18
	-----------------------------------------------
	-- INSERTANDO LOS DATOS DE LA NUEVA VENTA
	INSERT INTO Venta_cab VALUES(@NUMERO,GETDATE(),
		@CLI_COD,'F', @IGV, 99,@VTA_TOTAL)
	-- DEVOLVIENDO EL NUEVO NUMERO DE VENTA GENERADO
	SELECT @NUMERO AS NUMERO
GO


CREATE PROC USP_GRABAR_VENTA_DET_WEB
@VTA_NUM INT, @ART_COD CHAR(5), 
@ART_CAN INT, @ART_PRE DECIMAL(8,2)
AS
	-- INSERTANDO EL NUEVO DETALLE DE LA FACTURA
	INSERT INTO Venta_det 
	   VALUES(@VTA_NUM,@ART_COD,@ART_CAN,@ART_PRE)
	-- ACTUALIZANDO EL STOCK DEL ARTICULO
	UPDATE Articulos 
		SET art_stk=art_stk - @ART_CAN 
	WHERE art_cod = @ART_COD
GO

/*
------------ COMPROBANDO LA INSERCIÓN DE LA VENTA ------------------
SELECT TOP(1) * FROM Venta_cab ORDER BY vta_num DESC
GO

SELECT TOP(1)WITH TIES * FROM Venta_det 
	ORDER BY vta_num DESC
GO
*/
